"""add codigo pdf remove stock_minimo

Revision ID: 43208155a47c
Revises: a0780ee93020
Create Date: 2026-06-10 20:31:11.463948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43208155a47c'
down_revision = 'a0780ee93020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pdf', sa.String(length=255), nullable=True))
        batch_op.drop_column('stock_minimo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_minimo', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('pdf')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
